# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"InsertOperation": "00_EditOperations.ipynb",
         "DeleteOperation": "00_EditOperations.ipynb",
         "ReplaceOperation": "00_EditOperations.ipynb",
         "EditOperation": "00_EditOperations.ipynb",
         "CompoundOperation": "00_EditOperations.ipynb",
         "getCondensedBasic": "01_CondenseEditOperations.ipynb",
         "getCondensedLoose": "01_CondenseEditOperations.ipynb",
         "getCondensedStrict": "01_CondenseEditOperations.ipynb",
         "AbstractMethod": "02_AbstractMethod.ipynb",
         "readAbstractMethodsFromFile": "03_IOUtils.ipynb",
         "writeAbstractMethodsToFile": "03_IOUtils.ipynb",
         "getYamlParameter": "03_IOUtils.ipynb",
         "runCommand": "03_IOUtils.ipynb",
         "HephaestusModel": "04_HephaestusModel.ipynb"}

modules = ["EditOperations.py",
           "CondenseEditOperations.py",
           "AbstractMethod.py",
           "IOUtils.py",
           "HephaestusModel.py"]

doc_url = "https://WM-SEMERU.github.io/hephaestus/"

git_url = "https://github.com/WM-SEMERU/hephaestus/tree/main/"

def custom_doc_links(name): return None
