# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"example_func": "00_example.ipynb"}

modules = ["example.py"]

doc_url = "https://WM-SEMERU.github.io/hephaestus/"

git_url = "https://github.com/WM-SEMERU/hephaestus/tree/main/"

def custom_doc_links(name): return None
