# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"func": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://user.github.io/hephaestus/"

git_url = "https://github.com/user/hephaestus/tree/branch/"

def custom_doc_links(name): return None
