# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/06_TrainModels.ipynb (unless otherwise specified).

__all__ = ['MODEL_BASE_DIR', 'DEFAULT_PARAMS_DIR', 'MODEL_DEFAULT_CONTROL', 'MODEL_DEFAULT_BASIC',
           'MODEL_DEFAULT_STRICT', 'MODEL_DEFAULT_LOOSE', 'GROUP1_PARAMS_DIR', 'MODEL_GROUP1_CONTROL',
           'MODEL_GROUP1_BASIC', 'MODEL_GROUP1_STRICT', 'MODEL_GROUP1_LOOSE']

# Cell
#hide
import os

import sys
sys.path.append("..")

from .DatasetConstruction import *
from .HephaestusModel import *

# Cell
#hide
MODEL_BASE_DIR = os.path.join("..", "models")

# Cell
#hide
DEFAULT_PARAMS_DIR = "default_params"

MODEL_DEFAULT_CONTROL = os.path.join(MODEL_BASE_DIR, DEFAULT_PARAMS_DIR, "control")
MODEL_DEFAULT_BASIC =   os.path.join(MODEL_BASE_DIR, DEFAULT_PARAMS_DIR, "basic_ops")
MODEL_DEFAULT_STRICT =  os.path.join(MODEL_BASE_DIR, DEFAULT_PARAMS_DIR, "strict_ops")
MODEL_DEFAULT_LOOSE =   os.path.join(MODEL_BASE_DIR, DEFAULT_PARAMS_DIR, "loose_ops")

# Cell
#hide
GROUP1_PARAMS_DIR = "group1_params"

MODEL_GROUP1_CONTROL = os.path.join(MODEL_BASE_DIR, GROUP1_PARAMS_DIR, "control")
MODEL_GROUP1_BASIC =   os.path.join(MODEL_BASE_DIR, GROUP1_PARAMS_DIR, "basic_ops")
MODEL_GROUP1_STRICT =  os.path.join(MODEL_BASE_DIR, GROUP1_PARAMS_DIR, "strict_ops")
MODEL_GROUP1_LOOSE =   os.path.join(MODEL_BASE_DIR, GROUP1_PARAMS_DIR, "loose_ops")